const countryList = [
  {"name_en": "Afghanistan", "name_fr": "Afghanistan"},
  {"name_en": "Åland Islands", "name_fr": "Îles Åland"},
  {"name_en": "Albania", "name_fr": "Albanie"},
  {"name_en": "Algeria", "name_fr": "Algérie"},
  {"name_en": "American Samoa", "name_fr": "Samoa américaines"},
  {"name_en": "Andorra", "name_fr": "Andorre"},
  {"name_en": "Angola", "name_fr": "Angola"},
  {"name_en": "Anguilla", "name_fr": "Anguilla"},
  {"name_en": "Antarctica", "name_fr": "Antarctique"},
  {"name_en": "Antigua and Barbuda", "name_fr": "Antigua-et-Barbuda"},
  {"name_en": "Argentina", "name_fr": "Argentine"},
  {"name_en": "Armenia", "name_fr": "Arménie"},
  {"name_en": "Aruba", "name_fr": "Aruba"},
  {"name_en": "Australia", "name_fr": "Australie"},
  {"name_en": "Austria", "name_fr": "Autriche"},
  {"name_en": "Azerbaijan", "name_fr": "Azerbaïdjan"},
  {"name_en": "Bahamas (the)", "name_fr": "Bahamas (les)"},
  {"name_en": "Bahrain", "name_fr": "Bahreïn"},
  {"name_en": "Bangladesh", "name_fr": "Bangladesh"},
  {"name_en": "Barbados", "name_fr": "Barbade"},
  {"name_en": "Belarus", "name_fr": "Biélorussie"},
  {"name_en": "Belgium", "name_fr": "Belgique"},
  {"name_en": "Belize", "name_fr": "Belize"},
  {"name_en": "Benin", "name_fr": "Bénin"},
  {"name_en": "Bermuda", "name_fr": "Bermudes"},
  {"name_en": "Bhutan", "name_fr": "Bhoutan"},
  {"name_en": "Bolivia", "name_fr": "Bolivie"},
  {"name_en": "Bonaire, Sint Eustatius and Saba", "name_fr": "Bonaire, Saint-Eustache et Saba"},
  {"name_en": "Bosnia and Herzegovina", "name_fr": "Bosnie-Herzégovine"},
  {"name_en": "Botswana", "name_fr": "Botswana"},
  {"name_en": "Bouvet Island", "name_fr": "Île Bouvet"},
  {"name_en": "Brazil", "name_fr": "Brésil"},
  {"name_en": "British Indian Ocean Territory (the)", "name_fr": "Territoire britannique de l'océan Indien"},
  {"name_en": "Brunei Darussalam", "name_fr": "Brunéi Darussalam"},
  {"name_en": "Bulgaria", "name_fr": "Bulgarie"},
  {"name_en": "Burkina Faso", "name_fr": "Burkina Faso"},
  {"name_en": "Burundi", "name_fr": "Burundi"},
  {"name_en": "Cabo Verde", "name_fr": "Cabo Verde"},
  {"name_en": "Cambodia", "name_fr": "Cambodge"},
  {"name_en": "Cameroon", "name_fr": "Cameroun"},
  {"name_en": "Canada", "name_fr": "Canada"},
  {"name_en": "Cayman Islands (the)", "name_fr": "Îles Caïmans (les)"},
  {"name_en": "Central African Republic (the)", "name_fr": "République centrafricaine (la)"},
  {"name_en": "Chad", "name_fr": "Tchad"},
  {"name_en": "Chile", "name_fr": "Chili"},
  {"name_en": "China", "name_fr": "Chine"},
  {"name_en": "Christmas Island", "name_fr": "Île Christmas"},
  {"name_en": "Cocos (Keeling) Islands (the)", "name_fr": "Îles Cocos (Keeling)"},
  {"name_en": "Colombia", "name_fr": "Colombie"},
  {"name_en": "Comoros (the)", "name_fr": "Comores (les)"},
  {"name_en": "Congo (the Democratic Republic of the)", "name_fr": "Congo (la République démocratique du)"},
  {"name_en": "Congo (the)", "name_fr": "Congo (le)"},
  {"name_en": "Cook Islands (the)", "name_fr": "Îles Cook (les)"},
  {"name_en": "Costa Rica", "name_fr": "Costa Rica"},
  {"name_en": "Croatia", "name_fr": "Croatie"},
  {"name_en": "Cuba", "name_fr": "Cuba"},
  {"name_en": "Curaçao", "name_fr": "Curaçao"},
  {"name_en": "Cyprus", "name_fr": "Chypre"},
  {"name_en": "Czechia", "name_fr": "Tchéquie"},
  {"name_en": "Côte d'Ivoire", "name_fr": "Côte d'Ivoire"},
  {"name_en": "Denmark", "name_fr": "Danemark"},
  {"name_en": "Djibouti", "name_fr": "Djibouti"},
  {"name_en": "Dominica", "name_fr": "Dominique"},
  {"name_en": "Dominican Republic (the)", "name_fr": "République dominicaine (la)"},
  {"name_en": "Ecuador", "name_fr": "Équateur"},
  {"name_en": "Egypt", "name_fr": "Égypte"},
  {"name_en": "El Salvador", "name_fr": "El Salvador"},
  {"name_en": "Equatorial Guinea", "name_fr": "Guinée équatoriale"},
  {"name_en": "Eritrea", "name_fr": "Érythrée"},
  {"name_en": "Estonia", "name_fr": "Estonie"},
  {"name_en": "Eswatini", "name_fr": "Eswatini"},
  {"name_en": "Ethiopia", "name_fr": "Éthiopie"},
  {"name_en": "Falkland Islands (the) [Malvinas]", "name_fr": "Îles Malouines"},
  {"name_en": "Faroe Islands (the)", "name_fr": "Îles Féroé (les)"},
  {"name_en": "Fiji", "name_fr": "Fidji"},
  {"name_en": "Finland", "name_fr": "Finlande"},
  {"name_en": "France", "name_fr": "France"},
  {"name_en": "French Guiana", "name_fr": "Guyane française"},
  {"name_en": "French Polynesia", "name_fr": "Polynésie française"},
  {"name_en": "French Southern Territories (the)", "name_fr": "Terres australes françaises (les)"},
  {"name_en": "Gabon", "name_fr": "Gabon"},
  {"name_en": "Gambia (the)", "name_fr": "Gambie (la)"},
  {"name_en": "Georgia", "name_fr": "Géorgie"},
  {"name_en": "Germany", "name_fr": "Allemagne"},
  {"name_en": "Ghana", "name_fr": "Ghana"},
  {"name_en": "Gibraltar", "name_fr": "Gibraltar"},
  {"name_en": "Greece", "name_fr": "Grèce"},
  {"name_en": "Greenland", "name_fr": "Groenland"},
  {"name_en": "Grenada", "name_fr": "Grenade"},
  {"name_en": "Guadeloupe", "name_fr": "Guadeloupe"},
  {"name_en": "Guam", "name_fr": "Guam"},
  {"name_en": "Guatemala", "name_fr": "Guatemala"},
  {"name_en": "Guernsey", "name_fr": "Guernesey"},
  {"name_en": "Guinea", "name_fr": "Guinée"},
  {"name_en": "Guinea-Bissau", "name_fr": "Guinée-Bissau"},
  {"name_en": "Guyana", "name_fr": "Guyana"},
  {"name_en": "Haiti", "name_fr": "Haïti"},
  {"name_en": "Heard Island and McDonald Islands", "name_fr": "Îles Heard et McDonald"},
  {"name_en": "Holy See (the)", "name_fr": "Saint-Siège (le)"},
  {"name_en": "Honduras", "name_fr": "Honduras"},
  {"name_en": "Hong Kong", "name_fr": "Hong Kong"},
  {"name_en": "Hungary", "name_fr": "Hongrie"},
  {"name_en": "Iceland", "name_fr": "Islande"},
  {"name_en": "India", "name_fr": "Inde"},
  {"name_en": "Indonesia", "name_fr": "Indonésie"},
  {"name_en": "Iran", "name_fr": "Iran"},
  {"name_en": "Iraq", "name_fr": "Iraq"},
  {"name_en": "Ireland", "name_fr": "Irlande"},
  {"name_en": "Isle of Man", "name_fr": "Île de Man"},
  {"name_en": "Israel", "name_fr": "Israël"},
  {"name_en": "Italy", "name_fr": "Italie"},
  {"name_en": "Jamaica", "name_fr": "Jamaïque"},
  {"name_en": "Japan", "name_fr": "Japon"},
  {"name_en": "Jersey", "name_fr": "Jersey"},
  {"name_en": "Jordan", "name_fr": "Jordanie"},
  {"name_en": "Kazakhstan", "name_fr": "Kazakhstan"},
  {"name_en": "Kenya", "name_fr": "Kenya"},
  {"name_en": "Kiribati", "name_fr": "Kiribati"},
  {"name_en": "Korea (the Democratic People's Republic of)", "name_fr": "Corée (la République Populaire Démocratique de)"},
  {"name_en": "Korea (the Republic of)", "name_fr": "Corée (la République de)"},
  {"name_en": "Kuwait", "name_fr": "Koweït"},
  {"name_en": "Kyrgyzstan", "name_fr": "Kirghizistan"},
  {"name_en": "Laos", "name_fr": "Laos"},
  {"name_en": "Latvia", "name_fr": "Lettonie"},
  {"name_en": "Lebanon", "name_fr": "Liban"},
  {"name_en": "Lesotho", "name_fr": "Lesotho"},
  {"name_en": "Liberia", "name_fr": "Libéria"},
  {"name_en": "Libya", "name_fr": "Libye"},
  {"name_en": "Liechtenstein", "name_fr": "Liechtenstein"},
  {"name_en": "Lithuania", "name_fr": "Lituanie"},
  {"name_en": "Luxembourg", "name_fr": "Luxembourg"},
  {"name_en": "Macao", "name_fr": "Macao"},
  {"name_en": "Madagascar", "name_fr": "Madagascar"},
  {"name_en": "Malawi", "name_fr": "Malawi"},
  {"name_en": "Malaysia", "name_fr": "Malaisie"},
  {"name_en": "Maldives", "name_fr": "Maldives"},
  {"name_en": "Mali", "name_fr": "Mali"},
  {"name_en": "Malta", "name_fr": "Malte"},
  {"name_en": "Marshall Islands (the)", "name_fr": "Îles Marshall (les)"},
  {"name_en": "Martinique", "name_fr": "Martinique"},
  {"name_en": "Mauritania", "name_fr": "Mauritanie"},
  {"name_en": "Mauritius", "name_fr": "Maurice"},
  {"name_en": "Mayotte", "name_fr": "Mayotte"},
  {"name_en": "Mexico", "name_fr": "Mexique"},
  {"name_en": "Micronesia (Federated States of)", "name_fr": "Micronésie (États fédérés de)"},
  {"name_en": "Moldova", "name_fr": "Moldavie"},
  {"name_en": "Monaco", "name_fr": "Monaco"},
  {"name_en": "Mongolia", "name_fr": "Mongolie"},
  {"name_en": "Montenegro", "name_fr": "Monténégro"},
  {"name_en": "Montserrat", "name_fr": "Montserrat"},
  {"name_en": "Morocco", "name_fr": "Maroc"},
  {"name_en": "Mozambique", "name_fr": "Mozambique"},
  {"name_en": "Myanmar", "name_fr": "Myanmar"},
  {"name_en": "Namibia", "name_fr": "Namibie"},
  {"name_en": "Nauru", "name_fr": "Nauru"},
  {"name_en": "Nepal", "name_fr": "Népal"},
  {"name_en": "Netherlands (the)", "name_fr": "Pays-Bas (les)"},
  {"name_en": "New Caledonia", "name_fr": "Nouvelle-Calédonie"},
  {"name_en": "New Zealand", "name_fr": "Nouvelle-Zélande"},
  {"name_en": "Nicaragua", "name_fr": "Nicaragua"},
  {"name_en": "Niger (the)", "name_fr": "Niger (le)"},
  {"name_en": "Nigeria", "name_fr": "Nigéria"},
  {"name_en": "Niue", "name_fr": "Niue"},
  {"name_en": "Norfolk Island", "name_fr": "Île Norfolk"},
  {"name_en": "Northern Mariana Islands (the)", "name_fr": "Îles Mariannes du Nord (les)"},
  {"name_en": "Norway", "name_fr": "Norvège"},
  {"name_en": "Oman", "name_fr": "Oman"},
  {"name_en": "Pakistan", "name_fr": "Pakistan"},
  {"name_en": "Palau", "name_fr": "Palaos"},
  {"name_en": "Palestine, State of", "name_fr": "Palestine, État de"},
  {"name_en": "Panama", "name_fr": "Panama"},
  {"name_en": "Papua New Guinea", "name_fr": "Papouasie-Nouvelle-Guinée"},
  {"name_en": "Paraguay", "name_fr": "Paraguay"},
  {"name_en": "Peru", "name_fr": "Pérou"},
  {"name_en": "Philippines (the)", "name_fr": "Philippines (les)"},
  {"name_en": "Pitcairn", "name_fr": "Pitcairn"},
  {"name_en": "Poland", "name_fr": "Pologne"},
  {"name_en": "Portugal", "name_fr": "Portugal"},
  {"name_en": "Puerto Rico", "name_fr": "Porto Rico"},
  {"name_en": "Qatar", "name_fr": "Qatar"},
  {"name_en": "Republic of North Macedonia", "name_fr": "République de Macédoine du Nord"},
  {"name_en": "Romania", "name_fr": "Roumanie"},
  {"name_en": "Russia", "name_fr": "Russie"},
  {"name_en": "Rwanda", "name_fr": "Rwanda"},
  {"name_en": "Réunion", "name_fr": "Réunion"},
  {"name_en": "Saint Barthélemy", "name_fr": "Saint-Barthélemy"},
  {"name_en": "Saint Helena, Ascension and Tristan da Cunha", "name_fr": "Sainte-Hélène, Ascension et Tristan da Cunha"},
  {"name_en": "Saint Kitts and Nevis", "name_fr": "Saint-Kitts-et-Nevis"},
  {"name_en": "Saint Lucia", "name_fr": "Sainte-Lucie"},
  {"name_en": "Saint Martin (French part)", "name_fr": "Saint-Martin (partie française)"},
  {"name_en": "Saint Pierre and Miquelon", "name_fr": "Saint-Pierre-et-Miquelon"},
  {"name_en": "Saint Vincent and the Grenadines", "name_fr": "Saint-Vincent-et-les-Grenadines"},
  {"name_en": "Samoa", "name_fr": "Samoa"},
  {"name_en": "San Marino", "name_fr": "Saint-Marin"},
  {"name_en": "Sao Tome and Principe", "name_fr": "Sao Tomé-et-Principe"},
  {"name_en": "Saudi Arabia", "name_fr": "Arabie saoudite"},
  {"name_en": "Senegal", "name_fr": "Sénégal"},
  {"name_en": "Serbia", "name_fr": "Serbie"},
  {"name_en": "Seychelles", "name_fr": "Seychelles"},
  {"name_en": "Sierra Leone", "name_fr": "Sierra Leone"},
  {"name_en": "Singapore", "name_fr": "Singapour"},
  {"name_en": "Sint Maarten (Dutch part)", "name_fr": "Saint-Martin (partie néerlandaise)"},
  {"name_en": "Slovakia", "name_fr": "Slovaquie"},
  {"name_en": "Slovenia", "name_fr": "Slovénie"},
  {"name_en": "Solomon Islands", "name_fr": "Îles Salomon"},
  {"name_en": "Somalia", "name_fr": "Somalie"},
  {"name_en": "South Africa", "name_fr": "Afrique du Sud"},
  {"name_en": "South Georgia and the South Sandwich Islands", "name_fr": "Géorgie du Sud et îles Sandwich du Sud"},
  {"name_en": "South Sudan", "name_fr": "Soudan du Sud"},
  {"name_en": "Spain", "name_fr": "Espagne"},
  {"name_en": "Sri Lanka", "name_fr": "Sri Lanka"},
  {"name_en": "Sudan", "name_fr": "Soudan"},
  {"name_en": "Suriname", "name_fr": "Suriname"},
  {"name_en": "Svalbard and Jan Mayen", "name_fr": "Svalbard et Jan Mayen"},
  {"name_en": "Sweden", "name_fr": "Suède"},
  {"name_en": "Switzerland", "name_fr": "Suisse"},
  {"name_en": "Syrian Arab Republic", "name_fr": "République arabe syrienne"},
  {"name_en": "Taiwan", "name_fr": "Taïwan"},
  {"name_en": "Tajikistan", "name_fr": "Tadjikistan"},
  {"name_en": "Tanzania", "name_fr": "Tanzanie"},
  {"name_en": "Thailand", "name_fr": "Thaïlande"},
  {"name_en": "Timor-Leste", "name_fr": "Timor-Leste"},
  {"name_en": "Togo", "name_fr": "Togo"},
  {"name_en": "Tokelau", "name_fr": "Tokélaou"},
  {"name_en": "Tonga", "name_fr": "Tonga"},
  {"name_en": "Trinidad and Tobago", "name_fr": "Trinité-et-Tobago"},
  {"name_en": "Tunisia", "name_fr": "Tunisie"},
  {"name_en": "Turkey", "name_fr": "Turquie"},
  {"name_en": "Turkmenistan", "name_fr": "Turkménistan"},
  {"name_en": "Turks and Caicos Islands (the)", "name_fr": "Îles Turques-et-Caïques (les)"},
  {"name_en": "Tuvalu", "name_fr": "Tuvalu"},
  {"name_en": "Uganda", "name_fr": "Ouganda"},
  {"name_en": "Ukraine", "name_fr": "Ukraine"},
  {"name_en": "United Arab Emirates (the)", "name_fr": "Émirats arabes unis (les)"},
  {"name_en": "United Kingdom (the)", "name_fr": "Royaume-Uni (le)"},
  {"name_en": "United States Minor Outlying Islands (the)", "name_fr": "Îles mineures éloignées des États-Unis (les)"},
  {"name_en": "United States of America (the)", "name_fr": "États-Unis d'Amérique (les)"},
  {"name_en": "Uruguay", "name_fr": "Uruguay"},
  {"name_en": "Uzbekistan", "name_fr": "Ouzbékistan"},
  {"name_en": "Vanuatu", "name_fr": "Vanuatu"},
  {"name_en": "Venezuela", "name_fr": "Venezuela"},
  {"name_en": "Vietnam", "name_fr": "Viet Nam"},
  {"name_en": "Wallis and Futuna", "name_fr": "Wallis-et-Futuna"},
  {"name_en": "Western Sahara", "name_fr": "Sahara occidental"},
  {"name_en": "Yemen", "name_fr": "Yémen"},
  {"name_en": "Zambia", "name_fr": "Zambie"},
  {"name_en": "Zimbabwe", "name_fr": "Zimbabwe"}
]

const languageList = [
  {"name_en": "Afrikaans", "name_fr": "Afrikaans"},
  {"name_en": "Albanian", "name_fr": "Albanais"},
  {"name_en": "Amharic", "name_fr": "Amharique"},
  {"name_en": "Arabic", "name_fr": "Arabe"},
  {"name_en": "Aragonese", "name_fr": "Aragonais"},
  {"name_en": "Armenian", "name_fr": "Arménien"},
  {"name_en": "Asturian", "name_fr": "Asturien"},
  {"name_en": "Azerbaijani", "name_fr": "Azerbaïdjanais"},
  {"name_en": "Basque", "name_fr": "Basque"},
  {"name_en": "Belarusian", "name_fr": "Biélorusse"},
  {"name_en": "Bengali", "name_fr": "Bengali"},
  {"name_en": "Bosnian", "name_fr": "Bosnien"},
  {"name_en": "Breton", "name_fr": "Breton"},
  {"name_en": "Bulgarian", "name_fr": "Bulgare"},
  {"name_en": "Catalan", "name_fr": "Catalan"},
  {"name_en": "Central Kurdish", "name_fr": "Kurde central"},
  {"name_en": "Chinese", "name_fr": "Chinois"},
  {"name_en": "Corsican", "name_fr": "Corse"},
  {"name_en": "Croatian", "name_fr": "Croate"},
  {"name_en": "Czech", "name_fr": "Tchèque"},
  {"name_en": "Danish", "name_fr": "Danois"},
  {"name_en": "Dutch", "name_fr": "Néerlandais"},
  {"name_en": "English", "name_fr": "Anglais"},
  {"name_en": "Esperanto", "name_fr": "Espéranto"},
  {"name_en": "Estonian", "name_fr": "Estonien"},
  {"name_en": "Faroese", "name_fr": "Féroïen"},
  {"name_en": "Filipino", "name_fr": "Filipino"},
  {"name_en": "Finnish", "name_fr": "Finnois"},
  {"name_en": "French", "name_fr": "Français"},
  {"name_en": "Galician", "name_fr": "Galicien"},
  {"name_en": "Georgian", "name_fr": "Géorgien"},
  {"name_en": "German", "name_fr": "Allemand"},
  {"name_en": "Greek", "name_fr": "Grec"},
  {"name_en": "Guarani", "name_fr": "Guarani"},
  {"name_en": "Gujarati", "name_fr": "Gujarati"},
  {"name_en": "Hausa", "name_fr": "Haoussa"},
  {"name_en": "Hawaiian", "name_fr": "Hawaïen"},
  {"name_en": "Hebrew", "name_fr": "Hébreu"},
  {"name_en": "Hindi", "name_fr": "Hindi"},
  {"name_en": "Hungarian", "name_fr": "Hongrois"},
  {"name_en": "Icelandic", "name_fr": "Islandais"},
  {"name_en": "Indonesian", "name_fr": "Indonésien"},
  {"name_en": "Interlingua", "name_fr": "Interlingua"},
  {"name_en": "Irish", "name_fr": "Irlandais"},
  {"name_en": "Italian", "name_fr": "Italien"},
  {"name_en": "Japanese", "name_fr": "Japonais"},
  {"name_en": "Kannada", "name_fr": "Kannada"},
  {"name_en": "Kazakh", "name_fr": "Kazakh"},
  {"name_en": "Khmer", "name_fr": "Khmer"},
  {"name_en": "Korean", "name_fr": "Coréen"},
  {"name_en": "Kurdish", "name_fr": "Kurde"},
  {"name_en": "Kyrgyz", "name_fr": "Kirghize"},
  {"name_en": "Lao", "name_fr": "Lao"},
  {"name_en": "Latin", "name_fr": "Latin"},
  {"name_en": "Latvian", "name_fr": "Letton"},
  {"name_en": "Lingala", "name_fr": "Lingala"},
  {"name_en": "Lithuanian", "name_fr": "Lituanien"},
  {"name_en": "Macedonian", "name_fr": "Macédonien"},
  {"name_en": "Malay", "name_fr": "Malais"},
  {"name_en": "Malayalam", "name_fr": "Malayalam"},
  {"name_en": "Maltese", "name_fr": "Maltais"},
  {"name_en": "Marathi", "name_fr": "Marathi"},
  {"name_en": "Mongolian", "name_fr": "Mongol"},
  {"name_en": "Nepali", "name_fr": "Népalais"},
  {"name_en": "Norwegian", "name_fr": "Norvégien"},
  {"name_en": "Norwegian Bokmål", "name_fr": "Norvégien Bokmål"},
  {"name_en": "Norwegian Nynorsk", "name_fr": "Norvégien Nynorsk"},
  {"name_en": "Occitan", "name_fr": "Occitan"},
  {"name_en": "Oriya", "name_fr": "Oriya"},
  {"name_en": "Oromo", "name_fr": "Oromo"},
  {"name_en": "Pashto", "name_fr": "Pachto"},
  {"name_en": "Persian", "name_fr": "Persan"},
  {"name_en": "Polish", "name_fr": "Polonais"},
  {"name_en": "Portuguese", "name_fr": "Portugais"},
  {"name_en": "Punjabi", "name_fr": "Pendjabi"},
  {"name_en": "Quechua", "name_fr": "Quechua"},
  {"name_en": "Romanian", "name_fr": "Roumain"},
  {"name_en": "Romansh", "name_fr": "Romanche"},
  {"name_en": "Russian", "name_fr": "Russe"},
  {"name_en": "Scottish Gaelic", "name_fr": "Gaélique écossais"},
  {"name_en": "Serbian", "name_fr": "Serbe"},
  {"name_en": "Serbo", "name_fr": "Serbo"},
  {"name_en": "Shona", "name_fr": "Shona"},
  {"name_en": "Sindhi", "name_fr": "Sindhi"},
  {"name_en": "Sinhala", "name_fr": "Sinhala"},
  {"name_en": "Slovak", "name_fr": "Slovaque"},
  {"name_en": "Slovenian", "name_fr": "Slovène"},
  {"name_en": "Somali", "name_fr": "Somali"},
  {"name_en": "Southern Sotho", "name_fr": "Sotho du Sud"},
  {"name_en": "Spanish", "name_fr": "Espagnol"},
  {"name_en": "Sundanese", "name_fr": "Soundanais"},
  {"name_en": "Swahili", "name_fr": "Swahili"},
  {"name_en": "Swedish", "name_fr": "Suédois"},
  {"name_en": "Tajik", "name_fr": "Tadjik"},
  {"name_en": "Tamil", "name_fr": "Tamoul"},
  {"name_en": "Tatar", "name_fr": "Tatar"},
  {"name_en": "Telugu", "name_fr": "Télougou"},
  {"name_en": "Thai", "name_fr": "Thaï"},
  {"name_en": "Tigrinya", "name_fr": "Tigrigna"},
  {"name_en": "Tongan", "name_fr": "Tongien"},
  {"name_en": "Turkish", "name_fr": "Turc"},
  {"name_en": "Turkmen", "name_fr": "Turkmène"},
  {"name_en": "Twi", "name_fr": "Twi"},
  {"name_en": "Ukrainian", "name_fr": "Ukrainien"},
  {"name_en": "Urdu", "name_fr": "Ourdou"},
  {"name_en": "Uyghur", "name_fr": "Ouïghour"},
  {"name_en": "Uzbek", "name_fr": "Ouzbek"},
  {"name_en": "Vietnamese", "name_fr": "Vietnamien"},
  {"name_en": "Walloon", "name_fr": "Wallon"},
  {"name_en": "Welsh", "name_fr": "Gallois"},
  {"name_en": "West Frisian", "name_fr": "Frison occidental"},
  {"name_en": "Xhosa", "name_fr": "Xhosa"},
  {"name_en": "Yiddish", "name_fr": "Yiddish"}, 
  {"name_en": "Yoruba", "name_fr": "Yoruba"}, 
  {"name_en": "Zulu", "name_fr": "Zoulou"}]
